name: otodo
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2  

  # CREATE UNIQUE ID
  uuid: ^3.0.5
  
  # STATE MANAGEMENT
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  mobx_codegen: ^2.0.5+2
  provider: ^6.0.2

  # RESPONSIVE
  flutter_screenutil: ^5.3.1
  kartal: ^2.3.1

  # DATA
  hive_flutter: ^1.1.0
  hive: ^2.0.6
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  
  # UI
  top_snackbar_flutter: ^1.0.2

  # 
  easy_localization: ^3.0.0
  auto_size_text: ^3.0.0
 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lang/
